version: '2'
services:
    apitracking-app:
        image: apitracking
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://apitracking-postgresql:5432/apitracking
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=apitracking-elasticsearch:9300
        ports:
            - 8080:8080
    apitracking-postgresql:
        extends:
            file: postgresql.yml
            service: apitracking-postgresql
    apitracking-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: apitracking-elasticsearch
