version: '2'
services:
    apitracking-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/apitracking/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=apitracking
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
